# Curriculum schedule for
# a) skip connection annealing
# b) training across trials
stages = dict(
    [('wcst', [dict(blockLen_mn=5.,
                 blockLen_sd=0.,
                 epLen=5,
                 batchSize=100,
                 ratio=0.10),
               dict(blockLen_mn=10.,
                 blockLen_sd=0.,
                 epLen=10,
                 batchSize=100,
                 ratio=0.10),
               dict(blockLen_mn=10.,
                 blockLen_sd=2.,
                 epLen=20,
                 batchSize=100,
                 ratio=0.10),
               dict(blockLen_mn=8.,
                 blockLen_sd=2.,
                 epLen=50,
                 batchSize=50,
                 ratio=0.10,
                 ruleSupWt=0.5),
               dict(thresh=2.5,
                 ratio=0.20,
                 ruleSupWt=0.0,
                 learning_rate=5e-4),
               dict(ratio=0.30,
                 learning_rate=2e-4),
               dict(ratio=0.40),
               dict(ratio=0.50),
               dict(ratio=0.60),
               dict(ratio=0.70),
               dict(ratio=0.80),
               dict(ratio=0.90),
               dict(ratio=1.00)]),

     ('2afc-reversal', [dict(ratio=0.10),
                        dict(ratio=0.20, learning_rate=5e-4),
                        dict(ratio=0.30),
                        dict(ratio=0.40, learning_rate=2e-4),
                        dict(ratio=0.50),
                        dict(ratio=0.60),
                        dict(ratio=0.70),
                        dict(ratio=0.80),
                        dict(ratio=0.90),
                        dict(ratio=1.00)]) ])
